### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by francescawaters** [francescawaters/Dive-Cornwall#1]
**User story**

As a local diver, I want to see a list of upcoming dives that I can attend.

**Acceptance criteria**

- [ ] The home page shows the next upcoming event.
- [ ] The events page shows a list of the future dive trips.

**Tasks**

- [ ] Add a HTML section on the home page with the next upcoming event.
- [ ] Add a HTML section on the events page with all the upcoming events.
- [ ] Style using bootstrap
- [ ] Add events with times, location, dive type, dive site, depth.
