### ISSUE TITLE
Detailed site information

### ISSUE THREAD

**Issue by francescawaters** [francescawaters/Dive-Cornwall#4]
**User Story:** 

As a potential event attendee, I want to view detailed information about each dive site so that I can decide if I want to attend.

**Acceptance Criteria:**

- [ ] Each dive is categorised into shore or boat dives
- [ ] On the relevant page, details of the dive includes the event name, date, time, location, and a detailed description.
- [ ] The section also includes any relevant images/map?

**Tasks:**

- [ ] Each event links to the relevant detailed dive site section
- [ ] The detailed dive site section includes the event name, date, time, location, and a detailed description.
- [ ] The page also includes any relevant images/map
